ServerEvents.recipes( event=> {

    event.remove( { id:'elevatorid:elevator_white' } )
    event.remove( { id:'elevatorid:elevator_orange' } )
    event.remove( { id:'elevatorid:elevator_magenta' } )
    event.remove( { id:'elevatorid:elevator_light_blue' } )
    event.remove( { id:'elevatorid:elevator_yellow' } )
    event.remove( { id:'elevatorid:elevator_lime' } )
    event.remove( { id:'elevatorid:elevator_pink' } )
    event.remove( { id:'elevatorid:elevator_gray' } )
    event.remove( { id:'elevatorid:elevator_light_gray' } )
    event.remove( { id:'elevatorid:elevator_cyan' } )
    event.remove( { id:'elevatorid:elevator_purple' } )
    event.remove( { id:'elevatorid:elevator_blue' } )
    event.remove( { id:'elevatorid:elevator_brown' } )
    event.remove( { id:'elevatorid:elevator_green' } )
    event.remove( { id:'elevatorid:elevator_red' } )
    event.remove( { id:'elevatorid:elevator_black' } )

})