ServerEvents.tags('item', event => {
    // Global tag Battery Buffer
        event.add('forge:baterry_buffer', 'gtceu:ulv_battery_buffer_4x')
        event.add('forge:baterry_buffer', 'gtceu:lv_battery_buffer_4x')
        event.add('forge:baterry_buffer', 'gtceu:mv_battery_buffer_4x')
        event.add('forge:baterry_buffer', 'gtceu:hv_battery_buffer_4x')
        event.add('forge:baterry_buffer', 'gtceu:ev_battery_buffer_4x')
        event.add('forge:baterry_buffer', 'gtceu:iv_battery_buffer_4x')
        event.add('forge:baterry_buffer', 'gtceu:luv_battery_buffer_4x')
        event.add('forge:baterry_buffer', 'gtceu:zpm_battery_buffer_4x')
        event.add('forge:baterry_buffer', 'gtceu:uv_battery_buffer_4x')
        event.add('forge:baterry_buffer', 'gtceu:uhv_battery_buffer_4x')
        event.add('forge:baterry_buffer', 'gtceu:uev_battery_buffer_4x')
        event.add('forge:baterry_buffer', 'gtceu:uiv_battery_buffer_4x')
        event.add('forge:baterry_buffer', 'gtceu:uxv_battery_buffer_4x')
        event.add('forge:baterry_buffer', 'gtceu:opv_battery_buffer_4x')
        event.add('forge:baterry_buffer', 'gtceu:max_battery_buffer_4x')
    
        event.add('forge:baterry_buffer', 'gtceu:ulv_battery_buffer_8x')
        event.add('forge:baterry_buffer', 'gtceu:lv_battery_buffer_8x')
        event.add('forge:baterry_buffer', 'gtceu:mv_battery_buffer_8x')
        event.add('forge:baterry_buffer', 'gtceu:hv_battery_buffer_8x')
        event.add('forge:baterry_buffer', 'gtceu:ev_battery_buffer_8x')
        event.add('forge:baterry_buffer', 'gtceu:iv_battery_buffer_8x')
        event.add('forge:baterry_buffer', 'gtceu:luv_battery_buffer_8x')
        event.add('forge:baterry_buffer', 'gtceu:zpm_battery_buffer_8x')
        event.add('forge:baterry_buffer', 'gtceu:uv_battery_buffer_8x')
        event.add('forge:baterry_buffer', 'gtceu:uhv_battery_buffer_8x')
        event.add('forge:baterry_buffer', 'gtceu:uev_battery_buffer_8x')
        event.add('forge:baterry_buffer', 'gtceu:uiv_battery_buffer_8x')
        event.add('forge:baterry_buffer', 'gtceu:uxv_battery_buffer_8x')
        event.add('forge:baterry_buffer', 'gtceu:opv_battery_buffer_8x')
        event.add('forge:baterry_buffer', 'gtceu:max_battery_buffer_8x')
    
        event.add('forge:baterry_buffer', 'gtceu:ulv_battery_buffer_16x')
        event.add('forge:baterry_buffer', 'gtceu:lv_battery_buffer_16x')
        event.add('forge:baterry_buffer', 'gtceu:mv_battery_buffer_16x')
        event.add('forge:baterry_buffer', 'gtceu:hv_battery_buffer_16x')
        event.add('forge:baterry_buffer', 'gtceu:ev_battery_buffer_16x')
        event.add('forge:baterry_buffer', 'gtceu:iv_battery_buffer_16x')
        event.add('forge:baterry_buffer', 'gtceu:luv_battery_buffer_16x')
        event.add('forge:baterry_buffer', 'gtceu:zpm_battery_buffer_16x')
        event.add('forge:baterry_buffer', 'gtceu:uv_battery_buffer_16x')
        event.add('forge:baterry_buffer', 'gtceu:uhv_battery_buffer_16x')
        event.add('forge:baterry_buffer', 'gtceu:uev_battery_buffer_16x')
        event.add('forge:baterry_buffer', 'gtceu:uiv_battery_buffer_16x')
        event.add('forge:baterry_buffer', 'gtceu:uxv_battery_buffer_16x')
        event.add('forge:baterry_buffer', 'gtceu:opv_battery_buffer_16x')
        event.add('forge:baterry_buffer', 'gtceu:max_battery_buffer_16x')    
    
    // Battery Buffer 4x
        event.add('forge:baterry_buffer_4x', 'gtceu:ulv_battery_buffer_4x')
        event.add('forge:baterry_buffer_4x', 'gtceu:lv_battery_buffer_4x')
        event.add('forge:baterry_buffer_4x', 'gtceu:mv_battery_buffer_4x')
        event.add('forge:baterry_buffer_4x', 'gtceu:hv_battery_buffer_4x')
        event.add('forge:baterry_buffer_4x', 'gtceu:ev_battery_buffer_4x')
        event.add('forge:baterry_buffer_4x', 'gtceu:iv_battery_buffer_4x')
        event.add('forge:baterry_buffer_4x', 'gtceu:luv_battery_buffer_4x')
        event.add('forge:baterry_buffer_4x', 'gtceu:zpm_battery_buffer_4x')
        event.add('forge:baterry_buffer_4x', 'gtceu:uv_battery_buffer_4x')
        event.add('forge:baterry_buffer_4x', 'gtceu:uhv_battery_buffer_4x')
        event.add('forge:baterry_buffer_4x', 'gtceu:uev_battery_buffer_4x')
        event.add('forge:baterry_buffer_4x', 'gtceu:uiv_battery_buffer_4x')
        event.add('forge:baterry_buffer_4x', 'gtceu:uxv_battery_buffer_4x')
        event.add('forge:baterry_buffer_4x', 'gtceu:opv_battery_buffer_4x')
        event.add('forge:baterry_buffer_4x', 'gtceu:max_battery_buffer_4x')
    
    // Battery Buffer 8x
        event.add('forge:baterry_buffer_8x', 'gtceu:ulv_battery_buffer_8x')
        event.add('forge:baterry_buffer_8x', 'gtceu:lv_battery_buffer_8x')
        event.add('forge:baterry_buffer_8x', 'gtceu:mv_battery_buffer_8x')
        event.add('forge:baterry_buffer_8x', 'gtceu:hv_battery_buffer_8x')
        event.add('forge:baterry_buffer_8x', 'gtceu:ev_battery_buffer_8x')
        event.add('forge:baterry_buffer_8x', 'gtceu:iv_battery_buffer_8x')
        event.add('forge:baterry_buffer_8x', 'gtceu:luv_battery_buffer_8x')
        event.add('forge:baterry_buffer_8x', 'gtceu:zpm_battery_buffer_8x')
        event.add('forge:baterry_buffer_8x', 'gtceu:uv_battery_buffer_8x')
        event.add('forge:baterry_buffer_8x', 'gtceu:uhv_battery_buffer_8x')
        event.add('forge:baterry_buffer_8x', 'gtceu:uev_battery_buffer_8x')
        event.add('forge:baterry_buffer_8x', 'gtceu:uiv_battery_buffer_8x')
        event.add('forge:baterry_buffer_8x', 'gtceu:uxv_battery_buffer_8x')
        event.add('forge:baterry_buffer_8x', 'gtceu:opv_battery_buffer_8x')
        event.add('forge:baterry_buffer_8x', 'gtceu:max_battery_buffer_8x')

    // Battery Buffer 16x
        event.add('forge:baterry_buffer_16x', 'gtceu:ulv_battery_buffer_16x')
        event.add('forge:baterry_buffer_16x', 'gtceu:lv_battery_buffer_16x')
        event.add('forge:baterry_buffer_16x', 'gtceu:mv_battery_buffer_16x')
        event.add('forge:baterry_buffer_16x', 'gtceu:hv_battery_buffer_16x')
        event.add('forge:baterry_buffer_16x', 'gtceu:ev_battery_buffer_16x')
        event.add('forge:baterry_buffer_16x', 'gtceu:iv_battery_buffer_16x')
        event.add('forge:baterry_buffer_16x', 'gtceu:luv_battery_buffer_16x')
        event.add('forge:baterry_buffer_16x', 'gtceu:zpm_battery_buffer_16x')
        event.add('forge:baterry_buffer_16x', 'gtceu:uv_battery_buffer_16x')
        event.add('forge:baterry_buffer_16x', 'gtceu:uhv_battery_buffer_16x')
        event.add('forge:baterry_buffer_16x', 'gtceu:uev_battery_buffer_16x')
        event.add('forge:baterry_buffer_16x', 'gtceu:uiv_battery_buffer_16x')
        event.add('forge:baterry_buffer_16x', 'gtceu:uxv_battery_buffer_16x')
        event.add('forge:baterry_buffer_16x', 'gtceu:opv_battery_buffer_16x')
        event.add('forge:baterry_buffer_16x', 'gtceu:max_battery_buffer_16x')

    }
)
