StartupEvents.registry('item', event=> {

    event.create('bad_stone_hammer', 'shovel')
    .texture('kubejs:item/pre_stone_age/bad_stone_hammer')
    .displayName('Кам\'яний молот')
    .tier('stone')
    .maxDamage(131)
    .attackDamageBaseline(1)
    .speedBaseline(-3.6)

    event.create('stone_pickaxe', 'pickaxe')
    .texture('kubejs:item/pre_stone_age/stone_pickaxe')
    .displayName('Кам\'яне кайло')
    .tier('stone')
    .maxDamage(131)
    .attackDamageBaseline(1)
    .speedBaseline(-2.8)

    event.create('stone_sword', 'sword')
    .texture('kubejs:item/pre_stone_age/stone_sword')
    .displayName('Кам\'яна меч')
    .tier('stone')
    .maxDamage(131)
    .attackDamageBaseline(3)
    .speedBaseline(-2.4)

    event.create('stone_axe', 'axe')
    .texture('kubejs:item/pre_stone_age/stone_axe')
    .displayName('Кам\'яна сокира')
    .tier('stone')
    .maxDamage(131)
    .attackDamageBaseline(7)
    .speedBaseline(-3.2)

    event.create('stone_shovel', 'shovel')
    .texture('kubejs:item/pre_stone_age/stone_shovel')
    .displayName('Кам\'яний лопата')
    .tier('stone')
    .maxDamage(131)
    .attackDamageBaseline(1.5)
    .speedBaseline(-3)

    event.create('stone_hoe', 'hoe')
    .texture('kubejs:item/pre_stone_age/stone_hoe')
    .displayName('Кам\'яний мотика')
    .tier('stone')
    .maxDamage(131)
    .attackDamageBaseline(-1)
    .speedBaseline(-2)


})