ServerEvents.recipes( event=> {

    event.remove( { id:"twilightforest:wood/twilight_oak_sign" } )
    event.remove( { id:"twilightforest:wood/twilight_oak_hanging_sign" } )
    event.remove( { id:"twilightforest:twilight_oak_boat" } )
    event.remove( { id:"twilightforest:twilight_oak_chest_boat" } )
    event.remove( { id:"twilightforest:wood/twilight_oak_planks" } )
    event.remove( { id:"twilightforest:wood/twilight_oak_slab" } )
    event.remove( { id:"twilightforest:wood/twilight_oak_button" } )
    event.remove( { id:"twilightforest:wood/twilight_oak_fence" } )
    event.remove( { id:"twilightforest:wood/twilight_oak_gate" } )
    event.remove( { id:"twilightforest:wood/twilight_oak_plate" } )
    event.remove( { id:"twilightforest:wood/twilight_oak_door" } )
    event.remove( { id:"twilightforest:wood/twilight_oak_trapdoor" } )
    event.remove( { id:"twilightforest:wood/twilight_oak_chest" } )
    event.remove( { id:"twilightforest:wood/twilight_oak_stairs" } )

    event.remove( { id:"twilightforest:wood/canopy_sign" } )
    event.remove( { id:"twilightforest:wood/canopy_hanging_sign" } )
    event.remove( { id:"twilightforest:canopy_boat" } )
    event.remove( { id:"twilightforest:canopy_chest_boat" } )
    event.remove( { id:"twilightforest:wood/canopy_planks" } )
    event.remove( { id:"twilightforest:wood/canopy_slab" } )
    event.remove( { id:"twilightforest:wood/canopy_button" } )
    event.remove( { id:"twilightforest:wood/canopy_fence" } )
    event.remove( { id:"twilightforest:wood/canopy_gate" } )
    event.remove( { id:"twilightforest:wood/canopy_plate" } )
    event.remove( { id:"twilightforest:wood/canopy_door" } )
    event.remove( { id:"twilightforest:wood/canopy_trapdoor" } )
    event.remove( { id:"twilightforest:wood/canopy_chest" } )
    event.remove( { id:"twilightforest:empty_canopy_bookshelf" } )
    event.remove( { id:"twilightforest:canopy_bookshelf" } )
    event.remove( { id:"twilightforest:wood/canopy_stairs" } )

    event.remove( { id:"twilightforest:wood/mangrove_sign" } )
    event.remove( { id:"twilightforest:wood/mangrove_hanging_sign" } )
    event.remove( { id:"twilightforest:mangrove_boat" } )
    event.remove( { id:"twilightforest:mangrove_chest_boat" } )
    event.remove( { id:"twilightforest:wood/mangrove_planks" } )
    event.remove( { id:"twilightforest:wood/mangrove_slab" } )
    event.remove( { id:"twilightforest:wood/mangrove_button" } )
    event.remove( { id:"twilightforest:wood/mangrove_fence" } )
    event.remove( { id:"twilightforest:wood/mangrove_gate" } )
    event.remove( { id:"twilightforest:wood/mangrove_plate" } )
    event.remove( { id:"twilightforest:wood/mangrove_door" } )
    event.remove( { id:"twilightforest:wood/mangrove_trapdoor" } )
    event.remove( { id:"twilightforest:wood/mangrove_chest" } )
    event.remove( { id:"twilightforest:wood/mangrove_stairs" } )

    event.remove( { id:"twilightforest:wood/dark_sign" } )
    event.remove( { id:"twilightforest:wood/dark_hanging_sign" } )
    event.remove( { id:"twilightforest:dark_boat" } )
    event.remove( { id:"twilightforest:dark_chest_boat" } )
    event.remove( { id:"twilightforest:wood/dark_planks" } )
    event.remove( { id:"twilightforest:wood/dark_slab" } )
    event.remove( { id:"twilightforest:wood/dark_button" } )
    event.remove( { id:"twilightforest:wood/dark_fence" } )
    event.remove( { id:"twilightforest:wood/dark_gate" } )
    event.remove( { id:"twilightforest:wood/dark_plate" } )
    event.remove( { id:"twilightforest:wood/dark_door" } )
    event.remove( { id:"twilightforest:wood/dark_trapdoor" } )
    event.remove( { id:"twilightforest:wood/dark_chest" } )
    event.remove( { id:"twilightforest:wood/dark_stairs" } )

    event.remove( { id:"twilightforest:wood/time_sign" } )
    event.remove( { id:"twilightforest:wood/time_hanging_sign" } )
    event.remove( { id:"twilightforest:time_boat" } )
    event.remove( { id:"twilightforest:time_chest_boat" } )
    event.remove( { id:"twilightforest:wood/time_planks" } )
    event.remove( { id:"twilightforest:wood/time_slab" } )
    event.remove( { id:"twilightforest:wood/time_button" } )
    event.remove( { id:"twilightforest:wood/time_fence" } )
    event.remove( { id:"twilightforest:wood/time_gate" } )
    event.remove( { id:"twilightforest:wood/time_plate" } )
    event.remove( { id:"twilightforest:wood/time_door" } )
    event.remove( { id:"twilightforest:wood/time_trapdoor" } )
    event.remove( { id:"twilightforest:wood/time_chest" } )
    event.remove( { id:"twilightforest:wood/time_stairs" } )

    event.remove( { id:"twilightforest:wood/transformation_sign" } )
    event.remove( { id:"twilightforest:wood/transformation_hanging_sign" } )
    event.remove( { id:"twilightforest:transformation_boat" } )
    event.remove( { id:"twilightforest:transformation_chest_boat" } )
    event.remove( { id:"twilightforest:wood/transformation_planks" } )
    event.remove( { id:"twilightforest:wood/transformation_slab" } )
    event.remove( { id:"twilightforest:wood/transformation_button" } )
    event.remove( { id:"twilightforest:wood/transformation_fence" } )
    event.remove( { id:"twilightforest:wood/transformation_gate" } )
    event.remove( { id:"twilightforest:wood/transformation_plate" } )
    event.remove( { id:"twilightforest:wood/transformation_door" } )
    event.remove( { id:"twilightforest:wood/transformation_trapdoor" } )
    event.remove( { id:"twilightforest:wood/transformation_chest" } )
    event.remove( { id:"twilightforest:wood/transformation_stairs" } )

    event.remove( { id:"twilightforest:wood/mining_sign" } )
    event.remove( { id:"twilightforest:wood/mining_hanging_sign" } )
    event.remove( { id:"twilightforest:mining_boat" } )
    event.remove( { id:"twilightforest:mining_chest_boat" } )
    event.remove( { id:"twilightforest:wood/mining_planks" } )
    event.remove( { id:"twilightforest:wood/mining_slab" } )
    event.remove( { id:"twilightforest:wood/mining_button" } )
    event.remove( { id:"twilightforest:wood/mining_fence" } )
    event.remove( { id:"twilightforest:wood/mining_gate" } )
    event.remove( { id:"twilightforest:wood/mining_plate" } )
    event.remove( { id:"twilightforest:wood/mining_door" } )
    event.remove( { id:"twilightforest:wood/mining_trapdoor" } )
    event.remove( { id:"twilightforest:wood/mining_chest" } )
    event.remove( { id:"twilightforest:wood/mining_stairs" } )

    event.remove( { id:"twilightforest:wood/sorting_sign" } )
    event.remove( { id:"twilightforest:wood/sorting_hanging_sign" } )
    event.remove( { id:"twilightforest:sorting_boat" } )
    event.remove( { id:"twilightforest:sorting_chest_boat" } )
    event.remove( { id:"twilightforest:wood/sorting_planks" } )
    event.remove( { id:"twilightforest:wood/sorting_slab" } )
    event.remove( { id:"twilightforest:wood/sorting_button" } )
    event.remove( { id:"twilightforest:wood/sorting_fence" } )
    event.remove( { id:"twilightforest:wood/sorting_gate" } )
    event.remove( { id:"twilightforest:wood/sorting_plate" } )
    event.remove( { id:"twilightforest:wood/sorting_door" } )
    event.remove( { id:"twilightforest:wood/sorting_trapdoor" } )
    event.remove( { id:"twilightforest:wood/sorting_chest" } )
    event.remove( { id:"twilightforest:wood/sorting_stairs" } )


})