ServerEvents.recipes( event=> {

    event.remove( { id:"twilightforest:wood/twilight_oak_sign" } )
    event.remove( { id:"twilightforest:wood/twilight_oak_hanging_sign" } )
    event.remove( { id:"twilightforest:twilight_oak_boat" } )
    event.remove( { id:"twilightforest:twilight_oak_chest_boat" } )
    event.remove( { id:"twilightforest:wood/twilight_oak_planks" } )
    event.remove( { id:"twilightforest:wood/twilight_oak_slab" } )
    event.remove( { id:"twilightforest:wood/twilight_oak_button" } )
    event.remove( { id:"twilightforest:wood/twilight_oak_fence" } )
    event.remove( { id:"twilightforest:wood/twilight_oak_gate" } )
    event.remove( { id:"twilightforest:wood/twilight_oak_plate" } )
    event.remove( { id:"twilightforest:wood/twilight_oak_door" } )
    event.remove( { id:"twilightforest:wood/twilight_oak_trapdoor" } )
    event.remove( { id:"twilightforest:wood/twilight_oak_chest" } )
    event.remove( { id:"twilightforest:wood/twilight_oak_stairs" } )

    event.remove( { id:"twilightforest:wood/canopy_sign" } )
    event.remove( { id:"twilightforest:wood/canopy_hanging_sign" } )
    event.remove( { id:"twilightforest:canopy_boat" } )
    event.remove( { id:"twilightforest:canopy_chest_boat" } )
    event.remove( { id:"twilightforest:wood/canopy_planks" } )
    event.remove( { id:"twilightforest:wood/canopy_slab" } )
    event.remove( { id:"twilightforest:wood/canopy_button" } )
    event.remove( { id:"twilightforest:wood/canopy_fence" } )
    event.remove( { id:"twilightforest:wood/canopy_gate" } )
    event.remove( { id:"twilightforest:wood/canopy_plate" } )
    event.remove( { id:"twilightforest:wood/canopy_door" } )
    event.remove( { id:"twilightforest:wood/canopy_trapdoor" } )
    event.remove( { id:"twilightforest:wood/canopy_chest" } )
    event.remove( { id:"twilightforest:empty_canopy_bookshelf" } )
    event.remove( { id:"twilightforest:canopy_bookshelf" } )
    event.remove( { id:"twilightforest:wood/canopy_stairs" } )

    event.remove( { id:"twilightforest:wood/mangrove_sign" } )
    event.remove( { id:"twilightforest:wood/mangrove_hanging_sign" } )
    event.remove( { id:"twilightforest:mangrove_boat" } )
    event.remove( { id:"twilightforest:mangrove_chest_boat" } )
    event.remove( { id:"twilightforest:wood/mangrove_planks" } )
    event.remove( { id:"twilightforest:wood/mangrove_slab" } )
    event.remove( { id:"twilightforest:wood/mangrove_button" } )
    event.remove( { id:"twilightforest:wood/mangrove_fence" } )
    event.remove( { id:"twilightforest:wood/mangrove_gate" } )
    event.remove( { id:"twilightforest:wood/mangrove_plate" } )
    event.remove( { id:"twilightforest:wood/mangrove_door" } )
    event.remove( { id:"twilightforest:wood/mangrove_trapdoor" } )
    event.remove( { id:"twilightforest:wood/mangrove_chest" } )
    event.remove( { id:"twilightforest:wood/mangrove_stairs" } )

})