ServerEvents.recipes( event=>{

    event.remove( { id:"gtceu:alloy_smelter/iron_dust_and_nickel_dust_into_invar" } )
    event.remove( { id:"gtceu:alloy_smelter/wrought_iron_dust_and_nickel_ingot_into_invar" } )
    event.remove( { id:"gtceu:alloy_smelter/wrought_iron_dust_and_nickel_dust_into_invar" } )
    event.remove( { id:"gtceu:alloy_smelter/wrought_iron_ingot_and_nickel_dust_into_invar" } )
    event.remove( { id:"gtceu:alloy_smelter/wrought_iron_ingot_and_nickel_ingot_into_invar" } )
    event.remove( { id:"gtceu:alloy_smelter/iron_ingot_and_nickel_dust_into_invar" } )
    event.remove( { id:"gtceu:alloy_smelter/iron_ingot_and_nickel_ingot_into_invar" } )
    event.remove( { id:"gtceu:alloy_smelter/iron_dust_and_nickel_ingot_into_invar" } )
    event.remove( { id:"gtceu:electric_blast_furnace/blast_aluminium" } )
    event.remove( { id:"gtceu:electric_blast_furnace/blast_aluminium_gas" } )
    event.remove( { id:"gtceu:electric_blast_furnace/aluminium_from_green_sapphire_dust" } )
    event.remove( { id:"gtceu:electric_blast_furnace/aluminium_from_ruby_dust" } )
    event.remove( { id:"gtceu:electric_blast_furnace/aluminium_from_sapphire_dust" } )
    event.remove( { id:"gtceu:electric_blast_furnace/aluminium_from_ruby_gem" } )
    event.remove( { id:"gtceu:electric_blast_furnace/aluminium_from_sapphire_gem" } )
    event.remove( { id:"gtceu:electric_blast_furnace/aluminium_from_green_sapphire_gem" } )

})