
[config]

	[config.ktnilcks]

		[config.ktnilcks.section]

			[config.ktnilcks.section.versions]

				[config.ktnilcks.section.versions.config]

					[config.ktnilcks.section.versions.config.ktnilcks]

						[config.ktnilcks.section.versions.config.ktnilcks.notify]

							[config.ktnilcks.section.versions.config.ktnilcks.notify.global]
								#config.ktnilcks.notify.global.long
								short = false

							[config.ktnilcks.section.versions.config.ktnilcks.notify.chat]
								#config.ktnilcks.notify.chat.long
								short = false

							[config.ktnilcks.section.versions.config.ktnilcks.notify.hud]
								#config.ktnilcks.notify.hud.long
								short = true

			[config.ktnilcks.section.config]

				[config.ktnilcks.section.config.ktnilcks]

					[config.ktnilcks.section.config.ktnilcks.section]

						[config.ktnilcks.section.config.ktnilcks.section.actions]

							[config.ktnilcks.section.config.ktnilcks.section.actions.config]

								[config.ktnilcks.section.config.ktnilcks.section.actions.config.ktnilcks]

									[config.ktnilcks.section.config.ktnilcks.section.actions.config.ktnilcks.action]

										[config.ktnilcks.section.config.ktnilcks.section.actions.config.ktnilcks.action.bypassheld]
											#config.ktnilcks.action.bypassheld.long
											short = false

										[config.ktnilcks.section.config.ktnilcks.section.actions.config.ktnilcks.action.bypassall]
											#config.ktnilcks.action.bypassall.long
											short = false

										[config.ktnilcks.section.config.ktnilcks.section.actions.config.ktnilcks.action.bypassoffhand]
											#config.ktnilcks.action.bypassoffhand.long
											short = false

										[config.ktnilcks.section.config.ktnilcks.section.actions.config.ktnilcks.action.emptylock]
											#config.ktnilcks.action.emptylock.long
											short = false

						[config.ktnilcks.section.config.ktnilcks.section.config]

							[config.ktnilcks.section.config.ktnilcks.section.config.ktnilcks]

								[config.ktnilcks.section.config.ktnilcks.section.config.ktnilcks.section]

									[config.ktnilcks.section.config.ktnilcks.section.config.ktnilcks.section.hotbar]

										[config.ktnilcks.section.config.ktnilcks.section.config.ktnilcks.section.hotbar.config]

											[config.ktnilcks.section.config.ktnilcks.section.config.ktnilcks.section.hotbar.config.ktnilcks]

												[config.ktnilcks.section.config.ktnilcks.section.config.ktnilcks.section.hotbar.config.ktnilcks.hotbar]

													[config.ktnilcks.section.config.ktnilcks.section.config.ktnilcks.section.hotbar.config.ktnilcks.hotbar.visible]
														#config.ktnilcks.hotbar.visible.long
														short = true

