
#General Settings
[general]
	#Piglin Brute Drop Chance
	#Range: 0.0 ~ 1.0
	piglin_brute_drop_chance = 0.5
	#Piglin Drop Chance
	#Range: 0.0 ~ 1.0
	piglin_drop_chance = 0.25
	#Zombie Piglin Drop Chance
	#Range: 0.0 ~ 1.0
	zombie_piglin_drop_chance = 0.25

